### ISSUE TITLE
Exceuting VOTT on Linux

### ISSUE THREAD

**Issue by ahmedfsalhin** [CatalystCode/VOTT#110]
Trying to setup VOTT on azure data science VM. The tool doesn't work on both Ubuntu and CentOS machines. It appears for 1 second in "top" in the terminal and disappears again.

**Comment by aribornstein** [comment]
Hi Ahmed,

Thanks for your interest in our tool and for bringing this to our attention.

I'll take a look this weekend to see whats going on. In the meantime can you let me know if you the tool works if you clone the git repo from master and use npm install and npm start.

Best,
-Ari

**Comment by ahmedfsalhin** [comment]
Hi Ari,

Thanks for your swift reply. Clone, npm install, npm start worked very fine. Thanks!

Kind Regards,

Ahmed

**Comment by vermaatul524** [comment]
Hi Ari, 
How we can improve the prediction accuracy after training a model and also how we speedy the training time. Presently, for training a faster rcnn with a larger size dataset of 13k testiamges and 2k positive images on 6GPU's takes around 3+ days. 

Kindly do suggest how to reduce this training time. Does multiprocessing helps.

Best regards
Atul

**Comment by Krshivam** [comment]
thank you

**Comment by GunjanChourasia** [comment]
Thank You!
