### ISSUE TITLE
VOTT is not support uncompressed video formats(opencv video export), only supports compressed video formats(ffmpeg,h264).

### ISSUE THREAD

**Issue by whaozl** [CatalystCode/VOTT#120]

**Comment by aribornstein** [comment]
Thanks for the feedback I will evaluate this on the backend Vott is using the html5 video component so any file type that works will should work. What kind of files do you need supported specifically?

**Comment by whaozl** [comment]
Thank you very much, I use opencv3.2(python3.5 win10) to write many pictures into video and found can not be used in the VOTT, because the video of opencv3.2(python3.5 win10) exporting is not compressed video. the python3 code is :
```
jpegPaths=["F:\anjos\images\1.jpg","F:\anjos\images\2.jpg","F:\anjos\images\3.jpg","F:\anjos\images\4.jpg","F:\anjos\images\5.jpg","F:\anjos\images\6.jpg","F:\anjos\images\7.jpg",...,"F:\anjos\images\1000.jpg"]
video_path="F:\anjos\video\1.mp4"
fourcc = cv2.VideoWriter_fourcc('D', 'I', 'V', 'X')
fps=10
width, height=800,600
out = cv2.VideoWriter(video_path, fourcc, fps, (width, height))
for path in jpegPaths:
    img=cv2.imread(path)
    #cv2.imshow("shiyan", img)
    #cv2.waitKey(1)
    out.write(img)
out.release()
```
jpegPaths is 1000 pictures, I Omitted the part code. Picture resolution is 800X600.

I very much hope that VOTT can support uncompressed mpeg video. This is my video format by opencv3.2 python3.5 and VOTT sample video format.

![_20170529220418](https://cloud.githubusercontent.com/assets/6327360/26552840/8535d540-44bb-11e7-810e-b53f01540575.png)

![_20170529220622](https://cloud.githubusercontent.com/assets/6327360/26552842/88350e1e-44bb-11e7-8f61-63e6ecdd56e1.png)


**But I use ffmpeg to format my opencv exporting video, and VOT can open. but can VOT directly open the python opencv exporting video?**

**Comment by aribornstein** [comment]
I will this to the backlog and take a look to see what I can do just to let you know there is a beta version of the app in the posterSupport branch that supports direct image tagging from a directory. I recommend you use that since it is much faster and more efficient for your use case. My plan is to merge the code next week.

Best of Luck,
- Ari

**Comment by whaozl** [comment]
Can you send a  download link for the beta version of supporting direct image tagging from a directory which Can be executed?

**Comment by aribornstein** [comment]
I will have one ready on sunday :)

**Comment by whaozl** [comment]
Thank you very much for your helps!

**Comment by aribornstein** [comment]
Here is the new version with image support I have updated the documentation. Sorry about the delay. Let me know if you have any feedback.

https://github.com/CatalystCode/VOTT/releases/tag/v1.0.5
 
Best,
-Ari

**Comment by whaozl** [comment]
Thank you very much. I I have a suggestion, at the beginning tagging bbox, Can we only click on two points (the upper left corner and the bottom right corner), directly show this bbox? This will be tagged much faster.

**Comment by aribornstein** [comment]
Create a new issue for the feature and I'll add it to the back log.

**Comment by whaozl** [comment]
OK.

**Comment by PhatThai** [comment]
I have the same problem with videos created by opencv in VOTT version 2.1.0. I use ubuntu 18.04. Can you help me with this?
