### ISSUE TITLE
Export Format Yolo, the bbox txt is all Infinity Infinity Infinity Infinity

### ISSUE THREAD

**Issue by whaozl** [CatalystCode/VOTT#125]
Export Format Yolo, the bbox txt is all Infinity Infinity Infinity Infinity

**Comment by aribornstein** [comment]
I will take a look can you send me example output..

**Comment by whaozl** [comment]
@aribornstein 
![1](https://user-images.githubusercontent.com/6327360/27346348-74669d56-561f-11e7-8c04-97e7a7838976.png)
![2](https://user-images.githubusercontent.com/6327360/27346351-7707984e-561f-11e7-932a-28c0ab1504f1.png)

Now, I am anxious to turn to yolo, please help me solve, thank you.

**Comment by aribornstein** [comment]
It looks like there is a scaling error in the image support version of the code. I will hopefully have some time to resolve in the upcoming week.  In the meantime it might be worth while to look at the CNTK FastRCNN option. https://github.com/Microsoft/CNTK/wiki/Object-Detection-using-Fast-R-CNN

**Comment by aribornstein** [comment]
I've identified whats causing the problem and am working to resolve it. It's caused by the fact that while video frames all have the same dimensions images don't. I will update you once this is fixed.

**Comment by aribornstein** [comment]
Should be resolved now try the new version :)
