### ISSUE TITLE
Selecting directory of JPGs, viewer is just blank

### ISSUE THREAD

**Issue by rtrahms** [CatalystCode/VOTT#127]
Hi!
Thanks for developing this tool - I have tried it out on videos.  Making training data sets for YOLO quite a bit more efficient!

I wanted to try a directory of JPGs as well, didn't have the same success.  When I selected the directory, the viewer just shows a blank screen.  I know the app is aware of the JPGs, because the file names in the directory show up in the lower part of the window.

Is there a filename convention, or some other reason this isn't working?

Thanks again,
Rob

**Comment by rtrahms** [comment]
I figured out the issue.  JPG filenames that have either spaces or non-standard characters (like '(' or ')') are ignored.  I can work around this issue now that I know what it is.  Thanks.
Rob

**Comment by aribornstein** [comment]
Thanks for bringing this to my attention i will try to find a way of doing path validation in the next release.
