### ISSUE TITLE
In window bar show full path with file name

### ISSUE THREAD

**Issue by IevgenBelobrov** [CatalystCode/VoTT#130]
In window bar show full path with file name (now I can see just path to DataSet path)

**Comment by aribornstein** [comment]
Can you clarify what you mean by window bar?

**Comment by IevgenBelobrov** [comment]
Yes, I'm talking about tagging proc and application window Bar
![image](https://user-images.githubusercontent.com/29124347/27868938-feb99886-61a6-11e7-84a4-e7bceedb071a.png)

**Comment by aribornstein** [comment]
if you hit the next key you should see the path name.
