### ISSUE TITLE
AVI Video Support

### ISSUE THREAD

**Issue by rtrahms** [CatalystCode/VoTT#131]
Feature enhancement request:  Support for AVI format video files.

Thanks!
Rob

**Comment by aribornstein** [comment]
I'll add to the backlog  for the next release.

**Comment by rtrahms** [comment]
Thanks!

**Comment by aribornstein** [comment]
I looked into this unfortunately the html5 video control that we are using to load videos does not support avi. I recommend using ffmpeg to convert the video until a better solution can be found.
