### ISSUE TITLE
YOLO export format error on train.txt & test.txt

### ISSUE THREAD

**Issue by rtrahms** [CatalystCode/VoTT#133]
Missing new line between test images paths in each of these files.
Thanks,
Rob

**Comment by aribornstein** [comment]
i'll at a look today

**Comment by rtrahms** [comment]
Thanks!  I was able to work around it by updating the files manually.  By the way, these exported files worked in my training test for yolo!  Nice work.
Rob

**Comment by aribornstein** [comment]
Glad the tool worked for you :) I'm fixing the issue today.
