### ISSUE TITLE
Go to first untagged frame button doesn't appear to work

### ISSUE THREAD

**Issue by rtrahms** [CatalystCode/VoTT#137]
Is this a known issue?  I am not seeing anything advance when I press it.  Not a big deal, I manually advance to the frame in question using the other buttons.  Just noticed this one.

**Comment by aribornstein** [comment]
this is fixed in the lastest code if you use node. I will release a new binary at the end of the week

**Comment by rtrahms** [comment]
Thanks!  I'll pull the binary next week.
