### ISSUE TITLE
How to merge VOTT jsons?

### ISSUE THREAD

**Issue by rtrahms** [CatalystCode/VoTT#138]
Hi -
If there is more than one JPG folder/JSON in development, is there a way to combine/merge them such that the tagging work doesn't have to be redone on either?  Assuming the image file names are unique, collecting them all under the same folder wouldn't be a problem.  How about merging the JSON files?
Thanks,
Rob

**Comment by aribornstein** [comment]
This is out of scope for the tool. Probably the best way to do this is to read in the config files as two JSON objects using require and then merge their frames property using a map function.

The code would look something similar to the following prototype (not tested): 

```js
var config = require('config1.json');
var config2 = require('config2.json');

Object.keys(config.frames).map( (key, index) => {
   config.frames[key].concat( config2.frames[key]);
});
```

Best of luck,
-Ari
