### ISSUE TITLE
Loaded images are not showing in the application window

### ISSUE THREAD

**Issue by Aminullah6264** [CatalystCode/VoTT#139]
Hello everyone 
when i load images directory, all images are loaded but images are not displaying to select ROIs, in application window.

this can be seen in image that 96 images are loaded but no one is coming in display.

![aaa](https://user-images.githubusercontent.com/15268491/28957413-c39a49e2-792c-11e7-89e8-1b2651844967.PNG)

**Comment by Aminullah6264** [comment]
@aribornstein ^^^^^^^^^^^^^^^^

**Comment by Aminullah6264** [comment]
@aribornstein could you help me in this issue

**Comment by aribornstein** [comment]
Hi taking a look now this may be caused by the fact that your file names have spaces. Can you try to remove the spaces and confirm.

Best,
-Ari

**Comment by Aminullah6264** [comment]
Thanks @aribornstein 
i works for me, firstly i removed spaces from images names then it loaded correctly.

**Comment by ozdeger** [comment]
i am having the exact same issue but my file names doesnt have any spaces ....
