### ISSUE TITLE
YOLO format export bug: Need /r/n between nested objects

### ISSUE THREAD

**Issue by rtrahms** [CatalystCode/VoTT#140]
If one object class is nested within other object class in an image, exporting to YOLO format will result in a .txt file that has both detections on the same line - no CR/LF between them.

**Comment by aribornstein** [comment]
Can you post an example and i'll try to fix this. One thing to note is i am working on adding support for the new tensorflow object detection api when that is ready it might be worth checking out since they support training fasterRCNN and couple other Object Detection model options.

**Comment by rtrahms** [comment]
Say images exported for the yolo training set are data/obj/myImage1.jpg, data/obj/myImage2.jpg, etc.

The train.txt and test.txt files have the following listing (when read by darknet.exe and notepad.exe):

data/obj/myImage1.jpgdata/obj/myImage2.jpgdata/obj/myImage3.jpgdata/obj/myImage4.jpg etc

This is easily fixed by doing the following:
In a capable editor (like notepad++), replace jpg/ndata with jpg/n/rdata

After that, darknet.exe doesn't have a problem reading train.txt and test.txt.

Thanks,
Rob

**Comment by aribornstein** [comment]
Should be fixed with the latest release please confirm
