### ISSUE TITLE
Rename repository to be more generice (e.g., object-tagging object-tagging-app, visual-tagging...)

### ISSUE THREAD

**Issue by limorl** [CatalystCode/VOTT#98]

**Comment by aribornstein** [comment]
How about VOTT : Visual Object Tagging Tool

**Comment by limorl** [comment]
Like

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Mar 23, 2017 at 2:56 PM +0200, "PythicCoder" <notifications@github.com<mailto:notifications@github.com>> wrote:


How about VOTT : Visual Object Tagging Tool
